# Generated by Django 4.2.1 on 2023-05-04 15:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('map_code', models.TextField()),
                ('min_price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('meter_price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='residential_complex/photos/')),
                ('sea_distance', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('gas', models.BooleanField(default=True)),
                ('electricity', models.BooleanField(default=True)),
                ('house_status', models.CharField(choices=[('flats', 'Квартири'), ('cottage', 'Котедж'), ('many-floors', 'Многоэтажка'), ('secondary-market', 'Вторичный рынок')], default='flats', max_length=30)),
                ('house_type', models.CharField(choices=[('lux', 'Люкс'), ('elite', 'Элитный'), ('common', 'Стандартный')], default='common', max_length=30)),
                ('building_technology', models.CharField(choices=[('frame', 'Монолитный каркас'), ('foam', 'Пенобетон'), ('brick', 'Керпич')], default='brick', max_length=30)),
                ('territory', models.CharField(choices=[('close', 'Закрытая'), ('open', 'Открытая'), ('protected', 'Охраняемая')], default='close', max_length=30)),
                ('ceiling_height', models.IntegerField(choices=[(2, 'Two'), (3, 'There')], default=2, max_length=1)),
                ('heating', models.CharField(choices=[('central', 'Центральное')], default='central', max_length=30)),
                ('sewerage', models.CharField(choices=[('central', 'Центральное')], default='central', max_length=30)),
                ('water_supply', models.CharField(choices=[('central', 'Центральное')], default='central', max_length=30)),
                ('arrangement', models.CharField(choices=[('justice', 'Юстиція')], max_length=50)),
                ('payment', models.CharField(choices=[('mortgage', 'Ипотека'), ('parent-capital', 'Материнский капитал')], max_length=50)),
                ('contract_sum', models.CharField(choices=[('full', 'Полная'), ('part', 'Частями')], max_length=50)),
                ('property_status', models.CharField(choices=[('living_building', 'Жилое Помещение')], max_length=50)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.gallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
