# Generated by Django 4.2.1 on 2023-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='ceiling_height',
            field=models.IntegerField(choices=[(2, 'Two'), (3, 'There')], default=2),
        ),
    ]
